### ISSUE TITLE
Cannot load background-image element

### ISSUE THREAD

**Issue by L4Ph** [JuliusWiedemann/MarpThemeWave#1]
```css
:root {
    font-family: 'IBM Plex Sans JP', sans-serif;
    color: white;
    background-image: url("./background.svg");
    background-size: 100%;
}
```
![image](https://github.com/JuliusWiedemann/MarpThemeWave/assets/70247011/dd263519-2b03-4e2c-a440-cc21323df932)
